### ISSUE TITLE
Support local repositories processing

### ISSUE THREAD

**Issue by pierrelalanne** [GitGuardian/src-fingerprint#36]
## Context
A user might want to gather fingerprints for a local repository or a few local repositories.   
Where we could provide the user with the raw git command to launch, it could make sense to support this option natively in the tool.

## What to do
In this issue, we expect you to add a provider `local` for instance that will be dedicated to computing fingerprints for local repositories. The user should be able to specify a path. This provider will then list all available git repositories in this path, and compute fingerprints for them.  
Be sure to re-use the existing architecture as much as possible.

**Comment by Walz** [comment]
It's already possible with the provider `repository`. An example is given in the README.md under `Compute my code fingerprints` > `Repository` > `3. repository in a local directory`:

```sh
src-fingerprint -p repository -u /projects/gitlab/src-fingerprint
```
