### ISSUE TITLE
Complete doc to get fingerprints of private gitlab instance

### ISSUE THREAD

**Issue by AlexandraJerome** [GitGuardian/src-fingerprint#53]
## Context

I want to be able to gather the fingerprints from my private gitlab instance.

## DoD

- [ ] Add doc on the option `--provider-url`, which allow the user to specify the url of its private gitlab instance

ex: `src-fingerprint -v collect -p gitlab --provider-url https://myinstanceurl.com --token {my_token}`

- [ ] Add in doc : the personal access token needs to have read_api access to extract repositories

**Comment by pierrelalanne** [comment]
The Readme should be up to date now. Thanks for reporting @AlexandraJerome 🙂
